apiVersion: v1
kind: Service
metadata:
  name: azure-pipelines
  labels:
    app: azure-pipelines
    release: {{ .Release.Name }}
spec:
  ports:
    - name: http-az-p-port
      port: 80
      targetPort: az-p-port
      protocol: TCP
  selector:
    app: azure-pipelines
    release: {{ .Release.Name }}
